---
- name: Install httpd and git on Amazon Linux
  hosts: local
  connection: local
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install git
      yum:
        name: git
        state: present